### ISSUE TITLE
pain analysis

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#15]
- [x] extract pain variables

From doc from @holliebirkenshaw 

Pain:
“Pain”
“Pain intensity”
“Pain severity”
“Pain unpleasantness”
“Somatisation”

You might want to exclude “pain catastophising” and “pain interference” as pain by itself might pick these up

### tasks

- [x] create outcome in keywords
- [x] update keywords dataset
- [x] write exclusion code
- [x] write targets for pain
- [x] run targets
- [x] debug obs_pain

***
## data

- [ ] Output raw names for Hollie.
- [ ] also inclusion/exclusion criteria

***
## filters and engineering

- [x] filter to post intervention

***

- [x] network

### tasks

- [ ] write up model (hard)
- [x] get dummy workflow going

***

- [ ]  model output

***
- [ ] write up

### tasks

- [ ] multiple tabs
- this will be basis of shiny app
- [ ] 

***

- [ ] threshold analysis

**Comment by softloud** [comment]
## docs

- [ ] data
- [ ] output raw names
- [ ] output keywords
- [ ] network
- [ ] model output
- [ ] summary tables
