### ISSUE TITLE
reporting tables

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#16]
## What Tamar requested

- n of outcomes
- n of each pain group
- n of drugs

## tasks

- [ ] metatable from `summarise` of those for starters
- [ ] metatable with stats on all variables included in the analysis
- [ ] meet Cochrane standards
- [ ] look at how other nmas reported

### subtasks

- [ ] read in raw data

## notes

- measure types
