### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#38]
## objective

Clean data pipeline and document in such a way that Hollie can understand and check it.

Need to put together a protocol for each variable, possibly document in #43. 

## asserts

Check the outputs I'm expecting from the pipeline on modelling dataset.

positive or NA:
- [ ] mean
- [ ] r
- [ ] se
- [ ] sd

***
- [ ] n positive integer
- [ ] timepoint: post_int
- [ ] design: parallel

## inclusions and exclusions

- [ ] see #58 

### get the pipeline to run

- [x] pivot on scale, arm, study for all outcomes?

There are three points where information can be lost. 

Is there a way to compare the number of long-form obs with how many obs should be there? A count, perhaps on the pivot variables.

Filters
Wide
Viable

Document steps/variables

- [ ] raw
- [ ] input var table

## scales 

- [x] reread raw
- [x] bump to _before_ going wide, it is one of the identifying variables
- [x] replace spaces in scale category
- [ ] scale shorthand
- [ ] scale levels
- [ ] #54 

## interventions

- [ ] NA interventions
- [ ] labelling of interventions

## notes

- aggregate issues here for pipeline

## subissues

- [x] #20

**Comment by softloud** [comment]
```
source("R/scale_match.R")

library(glue)

df <- tar_read(w_obs_long_metapar)
tar_load(w_scales)

for (i in 1:nrow(df)) {
  message(glue("
   
               ***
               Row {i}
               *** "))
  
  scale_match(
    o = df$outcome[i],
    desc = df$covidence_desc[i],
    m = df$model_type[i],
    scale_df = w_scales
  )
}

```

![image](https://user-images.githubusercontent.com/13408706/130749681-5e474b6f-5544-43e0-b58c-d56fba872ed6.png)
